### ISSUE TITLE
Can't find CMSMS-Starter-Theme.xml

### ISSUE THREAD

**Issue by avhust** [FrontEndStudio/cmsms_starter_theme#1]
Hello Arnoud!

I'm looking forward to trying your approach, but I can't find basic CMSMS-Starter-Theme.xml file to import. Could you please point at the file?

**Comment by FrontEndStudio** [comment]
Thank you for your response. Will add it later today, till now there was no request for it.

**Comment by FrontEndStudio** [comment]
Added a file called Starter-Theme.xml enjoy.

https://github.com/FrontEndStudio/cmsms_starter_theme/commit/61926440c60ee8ddfffd9e194bcad68a08bfb5c4
